AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template creates the ElasticBeanstalk applications.
Parameters:
  EnvLabel:
    Description: Provide a label for your environment to identify resources easier.
    Type: String
  EC2KeyName:
    Type: String
    Description: This provides the name of the EC2 Key Pair to use.
  SSHSecurityGroup:
    Type: String
    Description: This provides the identifier of the security group to allow SSH from.
  SshToBeanstalk:
    Type: String
    Description: Allow SSH to this Beanstalk Environment
    AllowedValues:
      - 'yes'
      - 'no'
    Default: 'no'
  ParentVPCStack:
    Description: 'Stack name of the VPC stack based on EA-StandardVPC template.'
    Type: String
  InstanceTypes:
    Type: String
    Description: Size of the EC2 machines to host the Docker containers
    Default: t4g.medium,c6g.large
  BeanstalkMinInstances:
    Type: Number
    Description: Minimum Application Server Capacity for EB.
    Default: 1
  BeanstalkMaxInstances:
    Type: Number
    Description: Maximum Application Server Capacity for EB.
    Default: 3
  DomainName:
    Type: String
    Description: Domain Name for the environment
  HostedZoneId:
    Description: A Route53 HostedZone is required.  Select the zone for this environment.
    Type: AWS::Route53::HostedZone::Id
  DatabaseSecurityGroup:
    Description: ID of the Security Group containing the database server
    Type: String
  LogRetentionInDays:
    Description: Number of days to keep Beanstalk logs in CloudWatch Logs
    Type: Number
    Default: 365
  HealthCheckPath:
    Description: Application path for the load balancer to determine application health
    Type: String
    Default: /api/healthcheck
  UserPoolUrl:
    Description: Url For Validating User JWT values from an AWS Cognito Pool
    Type: String
  SnowSecret:
    Description: suffix portion of snowflake secret name in Secrets manager.  'EnvLabel-' will be prepended.
    Type: String
  CodeEnv:
    Description: Environment string that dictates which local config file is in use
    Type: String
  AppLauncherUrl:
    Description: Url for validating user JWT values against the app launcher API
    Type: String
  YopassUrl:
    Description: API Url for Yopass backend interactions.
    Type: String
  FrontEndUrl:
    Type: String
    Description: URL for front end
  CRHelperLambdaArn:
    Type: String
    Description: ARN of the CRHelper Lambda Layer
Conditions:
  AllowSshToBeanstalk: !Equals
    - !Ref 'SshToBeanstalk'
    - 'yes'
Resources:
  DbEncryptionSecretRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - secretsmanager:CreateSecret
                  - secretsmanager:UpdateSecret
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                  - secretsmanager:ListSecrets
                  - secretsmanager:TagResource
                  - secretsmanager:PutSecretValue
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${EnvLabel}-DBEncryptionSecret*'
            Version: '2012-10-17'
          PolicyName: !Sub ${EnvLabel}-DBEncryptionSecretPolicy
  DbEncryptionSecretLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Layers:
        - !Ref 'CRHelperLambdaArn'
      Description: creates and stores hex encoded byte strings to use as a DB encryption key and initialization vector.
      FunctionName: !Sub '${EnvLabel}-DbEncryptionSecret'
      Role: !GetAtt 'DbEncryptionSecretRole.Arn'
      Runtime: python3.9
      Timeout: 30
      Code:
        ZipFile: |
          import secrets
          import boto3
          import signal
          import json
          from crhelper import CfnResource

          helper = CfnResource()

          def lambda_handler(event, context):
              signal.alarm(int((context.get_remaining_time_in_millis() / 1000) - 1))
              helper(event, context)


          @helper.create
          def create(event, _):
              client = boto3.client('secretsmanager')
              envlabel = event['ResourceProperties']['envlabel']
              name = envlabel + '-DBEncryptionSecret'

              secret_exists = check_for_secret(name)

              if not secret_exists:
                  print("The secret named " + name + " did not exist...creating it now.")
                  key_token = secrets.token_hex(32)
                  iv_token = secrets.token_hex(16)
                  secret_dict = { "KEY": key_token, "IV": iv_token }

                  response = client.create_secret(
                      Name=name,
                      Description='Hex encoded byte strings to use as a DB encryption key and initialization vector.',
                      SecretString=json.dumps(secret_dict)
                  )

                  print("This secret was successfully created during the deployment and named " + name)
              else:
                  print("The secret named " + name + " ALREADY EXISTED in the AWS account and therefore the deployment DID NOT create a secret with this name.")


          def check_for_secret(secret_name):
              sm             = boto3.client('secretsmanager')
              response        = sm.list_secrets(
                  Filters=[
                      {
                          'Key': 'name',
                          'Values': [
                              secret_name
                          ]
                      }
                  ]
              )

              found = False

              for key in response['SecretList']:
                  if key['Name'] == secret_name:
                      found = True

              return found


          @helper.update
          def no_op(_, __):
              pass


          @helper.delete
          def delete(event, _):
              client = boto3.client('secretsmanager')
              envlabel = event['ResourceProperties']['envlabel']
              name = envlabel + '-DBEncryptionSecret'
              
              secret_exists = check_for_secret(name)
              
              if secret_exists:
                  print(f'Secret {name} was found. Deleting.')
                  client = boto3.client('secretsmanager')
                  response = client.delete_secret(
                      SecretId=name,
                      ForceDeleteWithoutRecovery=True
                  )
                  print(f'Secret {name} was deleted without recovery.')
              else:
                  print(f'Secret {name} was not found.')

          def timeout_handler(_signal, _frame):
              '''Handle SIGALRM'''
              raise Exception('lambda function timeout exceeded')


          signal.signal(signal.SIGALRM, timeout_handler)

  DbEncryptionSecretCustomResource:
    Type: AWS::CloudFormation::CustomResource
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      ServiceToken: !GetAtt DbEncryptionSecretLambda.Arn
      envlabel: !Ref EnvLabel
      region: !Ref AWS::Region
  ElasticBeanstalkEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier'
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker'
        - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      RoleName: !Sub '${EnvLabel}-elasticbeanstalk-ec2-role'
      Policies:
        - PolicyName: 'SecretsManager'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${EnvLabel}-*'
        - PolicyName: 'SBEMetadataAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: '*'
  ElasticBeanstalkEC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ElasticBeanstalkEC2Role
  BeanstalkEC2ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${EnvLabel}-Beanstalk'
      GroupDescription: !Sub 'Beanstalk managed servers for the ${EnvLabel} environment'
      VpcId: { 'Fn::ImportValue': !Sub '${ParentVPCStack}-VpcId' }
  DatabaseSecurityGroupInBeanstalk:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref DatabaseSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref BeanstalkEC2ServerSecurityGroup
  ALBHostNameRestrictionParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: !Sub 'Web traffic for the ${EnvLabel} environment must match this host-header.'
      Name: !Sub '/beanstalk/environments/${EnvLabel}-Env/parameters/ALBHostNameRestriction'
      Type: String
      Value: !Ref DomainName
  BeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Sub '${EnvLabel}-App'
      Description: !Sub '${EnvLabel}-App'
  BeanstalkSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${EnvLabel}-Beanstalk'
  BeanstalkSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref 'BeanstalkSNSTopic'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
              - SNS:Receive
            Resource: !Ref 'BeanstalkSNSTopic'
            Condition:
              StringEquals:
                AWS:SourceOwner: !Ref 'AWS::AccountId'
  BeanstalkEnvironment:
    DependsOn:
      - ALBHostNameRestrictionParameter
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref BeanstalkApplication
      Description: 'Beanstalk environment'
      EnvironmentName: !Sub '${EnvLabel}-Env'
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:sns:topics
          OptionName: Notification Topic ARN
          Value: !Ref 'BeanstalkSNSTopic'
        - Namespace: aws:elasticbeanstalk:healthreporting:system
          OptionName: ConfigDocument
          Value: |
            {
                "Version": 1,
                "Rules": {
                    "Environment": {
                        "Application": {
                            "ApplicationRequests4xx": {
                                "Enabled": false
                            }
                        },
                        "ELB": {
                            "ELBRequests4xx": {
                                "Enabled": false
                            }
                        }
                    }
                }
            }
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateEnabled
          Value: true
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: MaxBatchSize
          Value: 1
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: MinInstancesInService
          Value: !Ref 'BeanstalkMinInstances'
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateType
          Value: Health
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: Timeout
          Value: PT30M
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: !Ref 'BeanstalkMinInstances'
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: !Ref 'BeanstalkMaxInstances'
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: application
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: EC2KeyName
          Value: !If ['AllowSshToBeanstalk', !Ref EC2KeyName, !Ref AWS::NoValue]
        - Namespace: aws:ec2:instances
          OptionName: InstanceTypes
          Value: !Ref InstanceTypes
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref ElasticBeanstalkEC2InstanceProfile
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Ref BeanstalkEC2ServerSecurityGroup
        - !If
          - AllowSshToBeanstalk
          - Namespace: aws:autoscaling:launchconfiguration
            OptionName: SSHSourceRestriction
            Value: !Sub 'tcp,22,22,${SSHSecurityGroup}'
          - !Ref 'AWS::NoValue'
        - Namespace: aws:autoscaling:trigger
          OptionName: Unit
          Value: Percent
        - Namespace: aws:autoscaling:trigger
          OptionName: UpperThreshold
          Value: 60
        - Namespace: aws:autoscaling:trigger
          OptionName: LowerThreshold
          Value: 20
        - Namespace: aws:autoscaling:trigger
          OptionName: MeasureName
          Value: CPUUtilization
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: { 'Fn::ImportValue': !Sub '${ParentVPCStack}-VpcId' }
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: { 'Fn::ImportValue': !Sub '${ParentVPCStack}-PublicSubnets' }
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: { 'Fn::ImportValue': !Sub '${ParentVPCStack}-PrivateSubnets' }
        # - Namespace: aws:elasticbeanstalk:application
        #   OptionName: Application Healthcheck URL
        #   Value: /healthcheck
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: AWS_REGION
          Value: !Ref AWS::Region
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DATABASE_SECRET
          Value: !Sub '${EnvLabel}-PostgresMasterSecret'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: USER_POOL_URL
          Value: !Ref UserPoolUrl
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENVLABEL
          Value: !Ref EnvLabel
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: NODE_EXTRA_CA_CERTS
          Value: rds-combined-ca-bundle.pem
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: STWK_REJECT_UNAUTHORIZED
          Value: 'true'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: SNOW_SECRET
          Value: !Sub '${EnvLabel}-${SnowSecret}'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ACCESS_STUDENT_DATA_SECRET
          Value: !Sub '${EnvLabel}-BulkExportApiKey'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: CODE_ENV
          Value: !Ref CodeEnv
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: APP_LAUNCHER_URL
          Value: !Ref AppLauncherUrl
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: YOPASS_URL
          Value: !Ref YopassUrl
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DB_ENCRYPTION_SECRET
          Value: !Sub '${EnvLabel}-DbEncryptionSecret'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: MY_URL
          Value: !Sub 'https://${DomainName}'
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: FE_URL
          Value: !Ref FrontEndUrl
        - Namespace: aws:elasticbeanstalk:environment:process:https
          OptionName: Port
          Value: 443
        - Namespace: aws:elasticbeanstalk:environment:process:https
          OptionName: Protocol
          Value: HTTPS
        - Namespace: aws:elasticbeanstalk:environment:process:https
          OptionName: HealthCheckPath
          Value: !Ref HealthCheckPath
        - Namespace: aws:elbv2:listener:443
          OptionName: Protocol
          Value: HTTPS
        - Namespace: aws:elbv2:listener:443
          OptionName: SSLCertificateArns
          Value: !Ref x509Certificate
        - Namespace: aws:elbv2:listener:443
          OptionName: SSLPolicy
          Value: ELBSecurityPolicy-FS-1-2-Res-2020-10
        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: StreamLogs
          Value: true
        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: DeleteOnTerminate
          Value: true
        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: RetentionInDays
          Value: !Ref LogRetentionInDays
      SolutionStackName: !Sub 'arn:aws:elasticbeanstalk:${AWS::Region}::platform/Docker running on 64bit Amazon Linux 2'
      Tier:
        Name: 'WebServer'
        Type: 'Standard'
        Version: '1.0'
      # VersionLabel: !Ref BeanstalkVersion
      Tags:
        - Key: Environment
          Value: !Ref 'EnvLabel'
  x509Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
  AppRoute53record:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref DomainName
      HostedZoneId: !Ref HostedZoneId
      Type: CNAME
      TTL: 900
      ResourceRecords:
        - !GetAtt 'BeanstalkEnvironment.EndpointURL'
Outputs:
  EndpointURL:
    Description: The DNS name of the ELB
    Value: !GetAtt 'BeanstalkEnvironment.EndpointURL'
    Export:
      Name: !Sub '${AWS::StackName}-EndpointURL'
  EnvironmentName:
    Description: The name of the ElasticBeanstalk Environment.
    Value: !Ref 'BeanstalkEnvironment'
    Export:
      Name: !Sub '${AWS::StackName}-EnvironmentName'
  ApplicationName:
    Description: The name of the ElasticBeanstalk Application.
    Value: !Ref 'BeanstalkApplication'
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationName'
  BeanstalkSecurityGroup:
    Description: Security Group ID of the Beanstalk servers
    Value: !Ref 'BeanstalkEC2ServerSecurityGroup'
    Export:
      Name: !Sub '${AWS::StackName}-BeanstalkSecurityGroup'
  EnvLabel:
    Description: EnvLabel associated with this environment
    Value: !Ref 'EnvLabel'
    Export:
      Name: !Sub '${AWS::StackName}-EnvLabel'
