# This compose file defines the supporting services, Ed-Fi Admin App and Api.
# It is intended to be used in conjunction with the base edfi-docker-compose.yml file

name: edfiadminapp

services:
  edfiadminapp-keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_TAG:-26.1}
    container_name: edfiadminapp-keycloak
    ports:
      - '127.0.0.1:${KEYCLOAK_PORT_EXPOSED:-8080}:8080'
    volumes:
      - vol-edfiadminapp-keycloak:/opt/keycloak/data
      - ./adminapp/realm-config.json:/opt/keycloak/data/import/realm-config.json
      - ./adminapp/healthcheck.sh:/opt/keycloak/healthcheck.sh
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: false
      KC_HOSTNAME_STRICT: false
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_LOG_CONSOLE_LEVEL: ${KC_LOG_CONSOLE_LEVEL:-error}
      KC_LOG: file,console
      KC_HEALTH_ENABLED: true
    entrypoint:
      - sh
      - -c
      - |
        cp /opt/keycloak/healthcheck.sh /tmp/healthcheck.sh && \
        chmod +x /tmp/healthcheck.sh && \
        /opt/keycloak/bin/kc.sh start-dev --import-realm
    networks:
      - edfiadminapp-network
    healthcheck:
      test: ['CMD-SHELL', '/tmp/healthcheck.sh']
      interval: 20s
      timeout: 10s
      retries: 5

  # Use edfiadminapp-postgres for the Admin App api's data store with PostgreSQL
  edfiadminapp-postgres:
    image: postgres:${POSTGRESQL_IMAGE_TAG:-16.2}
    profiles:
      - postgresql
    container_name: edfiadminapp-postgres
    ports:
      - '127.0.0.1:${POSTGRES_PORT_EXPOSED:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${ADMIN_APP_DB_NAME:-sbaa}
    volumes:
      - vol-edfiadminapp-db:/var/lib/postgresql/data
    networks:
      - edfiadminapp-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Use edfiadminapp-mssql for the Admin App api's data store with SQL Server
  edfiadminapp-mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_IMAGE_TAG:-2022-latest}
    profiles:
      - mssql
    container_name: edfiadminapp-mssql
    ports:
      - '127.0.0.1:${MSSQL_PORT_EXPOSED:-1433}:1433'
    environment:
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA:-Y}
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_DB: ${ADMIN_APP_DB_NAME:-sbaa}
      MSSQL_PID: ${MSSQL_PID:-Express}
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        sleep 30s
        /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P  ${MSSQL_SA_PASSWORD} -Q "IF DB_ID(N'${MSSQL_DB:-sbaa}') IS NULL CREATE DATABASE [${MSSQL_DB:-sbaa}];"
        wait
    volumes:
      - vol-edfiadminapp-mssql:/var/opt/mssql
    networks:
      - edfiadminapp-network
    # TODO: needs a healthcheck

  memcached:
    image: memcached
    restart: always
    networks:
      - edfiadminapp-network

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - '127.0.0.1:8082:80'
    command: '--memcached=memcached:11211 --port 80'
    networks:
      - edfiadminapp-network

  edfiadminapp-api:
    build:
      context: ../
      dockerfile: packages/api/Dockerfile
    profiles:
      - adminapp
    container_name: edfiadminapp-api
    volumes:
      - api-logs:/app/logs
      - ./ssl/server.crt:/app/ssl/server.crt:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/app/ssl/server.crt
    extra_hosts:
      - 'localhost:host-gateway' # Allow container to access host's localhost
    external_links:
      - edfiadminapp-db:edfiadminapp-db
    restart: unless-stopped
    depends_on:
      edfiadminapp-db:
        condition: service_healthy
      edfiadminapp-keycloak:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/healthcheck || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    networks:
      - edfiadminapp-network

  edfiadminapp-fe:
    build:
      context: ../
      dockerfile: packages/fe/Dockerfile
    environment:
        # Change this to use the nginx proxy URL
        VITE_API_URL: ${VITE_API_URL:-https://localhost/adminapp-api}
        VITE_OIDC_ID: ${VITE_OIDC_ID:-1}
        VITE_BASE_PATH: '${VITE_BASE_PATH:-/adminapp/}'
        VITE_HELP_GUIDE: '${VITE_HELP_GUIDE:-https://docs.ed-fi.org/reference/admin-app-v4}'
        VITE_IDP_ACCOUNT_URL: '${VITE_IDP_ACCOUNT_URL:-https://localhost/auth/realms/edfi/account/}'
        VITE_STARTING_GUIDE: '${VITE_STARTING_GUIDE:-${VITE_HELP_GUIDE}/system-administrators/global-administration-tasks}'
        VITE_CONTACT: '${VITE_CONTACT:-https://community.ed-fi.org/}'
        VITE_APPLICATION_NAME: '${VITE_APPLICATION_NAME:-Ed-Fi Admin App}'
    profiles:
      - adminapp
    container_name: edfiadminapp-fe
    volumes:
      - ./adminapp/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      edfiadminapp-api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:4200/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - edfiadminapp-network

networks:
  edfiadminapp-network:
    external: true
    name: edfiadminapp-network

volumes:
  api-logs:
    driver: local
    name: vol-edfiadminapp-api-logs
  vol-edfiadminapp-db:
    driver: local
    name: vol-edfiadminapp-db
  vol-edfiadminapp-mssql:
    driver: local
    name: vol-edfiadminapp-mssql
  vol-edfiadminapp-keycloak:
    driver: local
    name: vol-edfiadminapp-keycloak
