
# This compose file defines the supporting services for local development of the Ed-Fi Admin App.
# It is intended to be used in conjunction with the base edfi-docker-compose.yml file
name: edfiadminapp-local-build

services:
  edfiadminapp-keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_TAG:-26.1}
    container_name: edfiadminapp-keycloak
    volumes:
      - vol-edfiadminapp-keycloak:/opt/keycloak/data
      # realm-config.json is copied via docker cp in start-local-dev.ps1 (not bind-mounted)
      # to allow template restoration without affecting the running container
      - ./adminapp/healthcheck.sh:/opt/keycloak/healthcheck.sh
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: false
      KC_HOSTNAME_STRICT: false
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_LOG_CONSOLE_LEVEL: ${KC_LOG_CONSOLE_LEVEL:-error}
      KC_LOG: file,console
      KC_HEALTH_ENABLED: "true"
    command:
      - start-dev
      - --import-realm
    networks:
      - edfiadminapp-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/keycloak/healthcheck.sh"]
      interval: 20s
      timeout: 10s
      retries: 5

  # Use edfiadminapp-db for the Admin App api's data store
  edfiadminapp-db:
    image: postgres:${POSTGRESQL_IMAGE_TAG:-16.2}
    container_name: edfiadminapp-db
    ports:
      - '127.0.0.1:${POSTGRES_PORT_EXPOSED:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${ADMIN_APP_DB_NAME:-sbaa}
    volumes:
      - vol-edfiadminapp-db:/var/lib/postgresql/data
    networks:
      - edfiadminapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  memcached:
    image: memcached
    restart: always
    networks:
      - edfiadminapp-network

  yopass:
    image: jhaals/yopass
    restart: always
    ports:
      - '127.0.0.1:8082:80'
    command: '--memcached=memcached:11211 --port 80'
    networks:
      - edfiadminapp-network

networks:
  edfiadminapp-network:
    external: true
    name: edfiadminapp-network

volumes:
  vol-edfiadminapp-db:
    driver: local
    name: vol-edfiadminapp-db
  vol-edfiadminapp-keycloak:
    driver: local
    name: vol-edfiadminapp-keycloak
