# This compose file defines the NGINX service for the Ed-Fi Admin App and supporting APIs.
name: nginx-compose

services:
  nginx:
    image: nginx:1.28.0-alpine3.21@sha256:8f2bcf97c473dfe311e79a510ee540ee02e28ce1e6a64e1ef89bfad32574ef10
    environment:
      ODS_v6_VIRTUAL_NAME: ${V6_ODS_VIRTUAL_NAME}
      ADMIN_API_v6_VIRTUAL_NAME: ${V6_ADMIN_API_VIRTUAL_NAME}
      V7_MULTI_API_VIRTUAL_NAME: ${V7_MULTI_API_VIRTUAL_NAME}
      V7_MULTI_ADMINAPI_VIRTUAL_NAME: ${V7_MULTI_ADMINAPI_VIRTUAL_NAME}
      V7_SINGLE_API_VIRTUAL_NAME: ${V7_SINGLE_API_VIRTUAL_NAME}
      V7_SINGLE_ADMIN_API_VIRTUAL: ${V7_SINGLE_ADMIN_API_VIRTUAL}
      # Note: this port must match the port in the `X-Forwarded-Port`
      # header in the `default.conf.template` file.
      EXTERNAL_PORT: 443
    ports:
      - '127.0.0.1:443:443'
    restart: always
    hostname: nginx
    container_name: nginx
    volumes:
      - ./ssl:/ssl/
      - ./settings/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - edfiadminapp-network

networks:
  edfiadminapp-network:
    external: true
    name: edfiadminapp-network


