#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 \
     --username "$POSTGRES_USER" \
     --dbname  "$POSTGRES_DB" <<-EOSQL
  CREATE USER "${ADMIN_APP_DB_USER}" WITH PASSWORD '${ADMIN_APP_DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${ADMIN_APP_DB_USER}";
  GRANT ALL ON SCHEMA public TO "${ADMIN_APP_DB_USER}";
EOSQL
